name: Publish NuGet Package with Tests

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Build and run tests
      run: |
        dotnet build -c Release australian-address-sanitiser/australian-address-sanitiser/australian-address-sanitiser.csproj
        dotnet test australian-address-sanitiser/australia-address-sanitiser-tests/australia-address-sanitiser-tests.csproj
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true

    - name: Pack and publish NuGet package
      run: |
        dotnet pack -c Release -o ./output australian-address-sanitiser/australian-address-sanitiser/australian-address-sanitiser.csproj
        dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true